# Use uma imagem base do Node.js
FROM node:23.0.0

# Define o diretório de trabalho dentro do container
WORKDIR /code

# Copia o package.json e o package-lock.json para o diretório de trabalho
COPY package*.json ./

# Instala as dependências do Node.js
RUN npm install

# Copia o restante do código da aplicação para o container
COPY . .

# Instala o Supervisor para gerenciar o processo Node.js
RUN apt-get update && apt-get install -y supervisor

# Cria o diretório para arquivos de configuração do Supervisor
RUN mkdir -p /etc/supervisor/conf.d

# Copia o arquivo de configuração do Supervisor para o container
COPY supervisord.conf /etc/supervisor/conf.d/nodejs-server.conf

# Expõe a porta na qual o Node.js está rodando (por exemplo, 3000)
EXPOSE 3000

# Comando para iniciar o Supervisor
CMD ["supervisord", "-n"]
