# Usa a imagem oficial do Node.js como base
FROM node:23.0.0

# Define o diretório de trabalho dentro do container
WORKDIR /code

# Copia o package.json e o package-lock.json para o diretório de trabalho
COPY package*.json ./

# Instala as dependências do Node.js
RUN npm install

# Copia o restante do código da aplicação para o container
COPY . .

# Constrói a aplicação React
RUN npm run build

# Instala um servidor simples para servir o build do React (como 'serve')
RUN npm install -g serve

# Expõe a porta na qual o servidor vai rodar (por exemplo, 3000)
EXPOSE 3000

# Comando para iniciar o servidor e servir o build React
CMD ["serve", "-s", "build", "-l", "3000"]
